name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Determine NPM dist-tag
        id: dist_tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ $VERSION == *-alpha* ]]; then
            TAG="alpha"
          elif [[ $VERSION == *-beta* ]]; then
            TAG="beta"
          elif [[ $VERSION == *-rc* ]]; then
            TAG="rc"
          else
            TAG="latest"
          fi
          echo "NPM_TAG=$TAG" >> $GITHUB_ENV
          echo "Determined tag: $TAG"

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public --tag ${{ env.NPM_TAG }}
